---
# Installs all system dependencies for Thumbor (native libs, image manipulation tools)

- name: Update apt index
  apt:
    update_cache: yes

- name: Install native dependencies for Thumbor image manipulation and python package compilation
  apt:
    name: "{{item}}"
    state: present
  with_items:
    # Libraries needed to compile the pycurl package (installed by thumbor):
    - libcurl4-openssl-dev
    - libssl-dev
    # Image libraries:
    - libtiff5-dev
    - libpng12-dev
    - libjpeg-dev
    - libjasper-dev
    - libwebp-dev

- name: Install supervisor package on older Ubuntus (where we don't use systemd)
  apt:
    name: supervisor
    state: present
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version < '15.04'

- name: Install Python 2 dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip # to get the pip package manager
    - python-dev # needed to build tornado (thumbors webserver) and potentially other python packages
    - python-pgmagick # image lib python

# This task is better run from the Ansible host as it needs a working AWS/Boto setup
# hence using delegate_to localhost
- name: Create result storage bucket on S3
  aws_s3:
    bucket: "{{ thumbor_result_storage_bucket }}"
    object: "/{{ thumbor_result_storage_path }}"
    mode: create
    region: "{{ s3_aws_region }}"
  # run on ansible host
  delegate_to: 127.0.0.1
  # use normal user on ansible host (avoids switching to root)
  become: false
  when: s3_create_bucket
